[tool.bumpver]
current_version = "1.11.0"
version_pattern = "MAJOR.MINOR.PATCH[-TAGNUM]"
commit_message = "chore: Bump version {old_version} -> {new_version}"
commit = true
fetch = true
tag = true
push = true

[tool.bumpver.file_patterns]
"composer.json" = [
    '"version": "{version}",',
]
"etc/config.xml" = [
    '<version>{version}</version>'
]
