<?php
/**
 * Copyright © Two.inc All rights reserved.
 * See COPYING.txt for license details.
 */

use ABN\Gateway\Block\Adminhtml\System\Config\Button\DebugCheck;

/**
 * @see \ABN\Gateway\Block\Adminhtml\System\Config\Button\DebugCheck
 * @var DebugCheck $block
 */
?>
<div id="two-result_debug-modal"
     data-two-endpoind-url="<?= $block->escapeUrl($block->getDebugCheckUrl()) ?>">
    <div id="two-result_debug">
        <div class="result"></div>
    </div>
</div>
<?= $block->getButtonHtml() ?>
