name: Merge main → develop

on:
  push:
    branches: [main]

concurrency:
  group: merge-main
  cancel-in-progress: true

jobs:
  merge-main:
    runs-on: ${{ vars.RUNNER_STANDARD }}
    if: github.ref_name == 'main'
    steps:
      - name: Merge or create pull request
        uses: two-inc/merge-or-pr-action@main
        with:
          client-id: ${{ vars.TWO_INC_APP_CLIENT_ID }}
          app-private-key: ${{ secrets.TWO_INC_APP_PRIVATE_KEY }}
          source-ref: main
          target-ref: develop
          reviewer: brtkwr
